jwt:
  secret: ZXN0YSBlcyB1bmEgcHJ1ZWJhIGRlIGZ1bmNpb25hbGlkYWQgZGUgdW5hIGFwbGljYWNpb24gY29uIHNwcmluZyBzZWN1cml0eQ==
  expiration: 10
server:
  error:
    include-message: always
  servlet:
    context-path: '/api/${VERSION:v1}'
  port: ${PORT:8080}
spring:
  application:
    name: security-user
  datasource:
    driverClassName: org.h2.Driver
    password: '${PASSWORD_DB:1234}'
    url: jdbc:h2:mem:testdb
    username: '${USER_DB:sa}'
  h2:
    console:
      enabled: true
      path: /auth/h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  packages-to-scan: ni.com.user.security.controller